So close...
Works in the synthetic hardware mode.

Once I tried it with the other hardware enabled, I get the following error:

  File "C:\Users\MicroscopyInnovation\Documents\GitHub\navigate\src\navigate\model\features\feature_container.py", line 556, in run
    result, is_end = self.curr_node.run(*args, wait_response=wait_response)
  File "C:\Users\MicroscopyInnovation\Documents\GitHub\navigate\src\navigate\model\features\feature_container.py", line 242, in run
    self.node_funcs["init"]()
  File "C:/Users/MicroscopyInnovation/Documents/GitHub/navigate-photoactivation/navigate-photoactivation\model\features\photoactivation.py", line 266, in pre_func_signal
    self.prepare_galvo_tasks()
  File "C:/Users/MicroscopyInnovation/Documents/GitHub/navigate-photoactivation/navigate-photoactivation\model\features\photoactivation.py", line 241, in prepare_galvo_tasks
    self.galvo_task.write(waveforms)
  File "C:\Users\MicroscopyInnovation\Anaconda3\envs\navigate\lib\site-packages\nidaqmx\task.py", line 1233, in write
    return _write_analog_f_64(
  File "C:\Users\MicroscopyInnovation\Anaconda3\envs\navigate\lib\site-packages\nidaqmx\_task_modules\write_functions.py", line 32, in _write_analog_f_64
    check_for_error(error_code)
  File "C:\Users\MicroscopyInnovation\Anaconda3\envs\navigate\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: Specified route cannot be satisfied, because it requires resources that are currently in use by another route.
Property: DAQmx_DigEdge_StartTrig_Src
Property: DAQmx_DigEdge_StartTrig_Edge
Source Device: PCIE6738
Source Terminal: Software

Required Resources in Use by
Task Name: _unnamedTask<17>
Source Device: PCIE6738
Source Terminal: PFI0
Destination Device: PCIE6738
Destination Terminal: ao/StartTrigger

Task Name: X & Y Galvo - Photoactivation

Status Code: -89137